# Generated by Django 4.2.19 on 2025-02-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='firstName',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastName',
            field=models.CharField(default='Doe', max_length=255),
        ),
    ]
