# Generated by Django 5.1.4 on 2025-01-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('digital_signature', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
