# Generated by Django 5.1.4 on 2025-03-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientManagement', '0002_remove_patient_name_patient_firstname_and_more'),
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_signature', to='patientManagement.patient'),
        ),
    ]
