# Generated by Django 4.2.19 on 2025-03-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientManagement', '0002_remove_patient_name_patient_firstname_and_more'),
        ('providerManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPatientConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_on', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientManagement.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providerManagement.provider')),
            ],
            options={
                'unique_together': {('provider', 'patient')},
            },
        ),
    ]
