# Generated by Django 5.2.3 on 2025-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerManagement', '0002_providerpatientconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
        migrations.AlterField(
            model_name='provider',
            name='firstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='lastName',
            field=models.CharField(max_length=255),
        ),
    ]
