# Generated by Django 4.2.19 on 2025-04-07 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveyManagement.multiplechoiceoption'),
        ),
    ]
