# Generated by Django 4.2.19 on 2025-04-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyManagement', '0002_alter_multiplechoiceresponse_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('completed', 'Completed')], default='sent', max_length=10),
        ),
    ]
