# Generated by Django 5.2.3 on 2026-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyManagement', '0004_populate_initial_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='is_multi_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplechoiceresponse',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='responses', to='surveyManagement.multiplechoiceoption'),
        ),
    ]
