# Generated by Django 5.2.3 on 2026-02-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyManagement', '0006_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceresponse',
            name='selected_option',
        ),
    ]
