# Generated by Django 5.1.4 on 2025-03-09 18:04

import django.db.models.deletion
import recordings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientManagement', '0002_remove_patient_name_patient_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=recordings.models.recording_file_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='patientManagement.patient')),
            ],
        ),
    ]
