# Generated by Django 4.2.19 on 2025-04-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientManagement', '0002_remove_patient_name_patient_firstname_and_more'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recording',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='patientManagement.patient'),
        ),
    ]
