# Generated by Django 4.2.19 on 2025-04-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientManagement', '0002_remove_patient_name_patient_firstname_and_more'),
        ('providerManagement', '0002_providerpatientconnection'),
        ('recordings', '0002_remove_recording_updated_at_recording_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('completed', 'Completed')], default='sent', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_requests_received', to='patientManagement.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_requests_sent', to='providerManagement.provider')),
                ('recording', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='recordings.recording')),
            ],
        ),
    ]
