# Generated by Django 5.2.3 on 2025-11-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientManagement', '0003_remove_patient_email_alter_patient_firstname_and_more'),
        ('providerManagement', '0003_remove_provider_email_alter_provider_firstname_and_more'),
        ('recordings', '0003_recordingrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordingrequest',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AddField(
            model_name='recordingrequest',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recordingrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='sent', max_length=10),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['patient', '-created_at'], name='recordings__patient_58bafc_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingrequest',
            index=models.Index(fields=['patient', 'status'], name='recordings__patient_cba34a_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingrequest',
            index=models.Index(fields=['provider', 'status'], name='recordings__provide_340400_idx'),
        ),
    ]
