# Generated by Django 5.2.3 on 2025-11-26 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientManagement', '0003_remove_patient_email_alter_patient_firstname_and_more'),
        ('recordings', '0004_alter_recordingrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='patientManagement.patient'),
            preserve_default=False,
        ),
    ]
