# Generated by Django 5.2.3 on 2026-01-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_alter_recording_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='analytics_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='VoiceAnalytics',
            fields=[
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='recordings.recording')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('insufficient_quality', 'Insufficient Quality')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.FloatField(blank=True, null=True)),
                ('ambient_noise_level', models.FloatField(blank=True, null=True)),
                ('signal_to_noise_ratio', models.FloatField(blank=True, null=True)),
                ('recording_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('quality_warnings', models.JSONField(blank=True, default=list)),
                ('jitter_local', models.FloatField(blank=True, null=True)),
                ('jitter_absolute', models.FloatField(blank=True, null=True)),
                ('jitter_rap', models.FloatField(blank=True, null=True)),
                ('jitter_ppq5', models.FloatField(blank=True, null=True)),
                ('jitter_ddp', models.FloatField(blank=True, null=True)),
                ('shimmer_local', models.FloatField(blank=True, null=True)),
                ('shimmer_db', models.FloatField(blank=True, null=True)),
                ('shimmer_apq3', models.FloatField(blank=True, null=True)),
                ('shimmer_apq5', models.FloatField(blank=True, null=True)),
                ('shimmer_apq11', models.FloatField(blank=True, null=True)),
                ('shimmer_dda', models.FloatField(blank=True, null=True)),
                ('f0_mean', models.FloatField(blank=True, null=True)),
                ('f0_min', models.FloatField(blank=True, null=True)),
                ('f0_max', models.FloatField(blank=True, null=True)),
                ('f0_std', models.FloatField(blank=True, null=True)),
                ('f0_voiced_frames', models.IntegerField(blank=True, null=True)),
                ('cpp_mean', models.FloatField(blank=True, null=True)),
                ('cpp_std', models.FloatField(blank=True, null=True)),
                ('hnr_mean', models.FloatField(blank=True, null=True)),
                ('hnr_min', models.FloatField(blank=True, null=True)),
                ('hnr_max', models.FloatField(blank=True, null=True)),
                ('ltas_slope', models.FloatField(blank=True, null=True)),
                ('ltas_tilt', models.FloatField(blank=True, null=True)),
                ('avqi_score', models.FloatField(blank=True, null=True)),
                ('avqi_interpretation', models.CharField(blank=True, choices=[('normal', 'Normal (0-2.3)'), ('borderline', 'Borderline (2.3-3.5)'), ('dysphonic', 'Dysphonic (3.5-10)')], max_length=20, null=True)),
                ('sample_type', models.CharField(default='unknown', max_length=20)),
                ('analysis_version', models.CharField(default='1.0', max_length=20)),
                ('raw_parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice Analytics',
                'verbose_name_plural': 'Voice Analytics',
                'db_table': 'voice_analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='voice_analy_status_2c3d48_idx'), models.Index(fields=['avqi_score'], name='voice_analy_avqi_sc_a72d95_idx'), models.Index(fields=['-created_at'], name='voice_analy_created_38bd17_idx')],
            },
        ),
    ]
